package bank;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import logic.FileManager;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.IOException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class CreateAccount extends javax.swing.JFrame {
    private AdminPanel adminPanel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccount.class.getName());

    /**
     * Creates new form CreateAccount
     */
public CreateAccount(AdminPanel panel) { 
    initComponents();
        getContentPane().setBackground(new java.awt.Color(228, 198, 168));
    this.adminPanel = panel; 
       String newAccNo = FileManager.generateAccountNumber();
    txtAccNo.setText(newAccNo);
    txtAccNo.setEditable(false);
// String newAccNo = FileManager.generateAccountNumber();
//    txtAccNo.setText(newAccNo);
//    txtAccNo.setEditable(false);// assign AdminPanel reference
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInitialBalance = new javax.swing.JTextField();
        btnCreateAcc = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account Holder Name");

        txtAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Initial Deposit");

        txtInitialBalance.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtInitialBalanceInputMethodTextChanged(evt);
            }
        });
        txtInitialBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInitialBalanceActionPerformed(evt);
            }
        });
        txtInitialBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInitialBalanceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInitialBalanceKeyTyped(evt);
            }
        });

        btnCreateAcc.setBackground(new java.awt.Color(102, 255, 204));
        btnCreateAcc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateAcc.setText("Create Account");
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 255, 204));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("      Account Number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtInitialBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreateAcc)
                        .addGap(57, 57, 57)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInitialBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAcc)
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNoActionPerformed


     // TODO add your handling code here:
    }//GEN-LAST:event_txtAccNoActionPerformed

private void saveAccountToCSV(AccountInfo acc) {

    String filePath = "accounts.csv";  // You can change directory if needed

    try (FileWriter fw = new FileWriter(filePath, true);
         BufferedWriter bw = new BufferedWriter(fw);
         PrintWriter out = new PrintWriter(bw)) {

        // Write data in CSV format
        out.println(acc.accNo + "," +
                    acc.name + "," +
                    acc.initialBalance + "," +
                    acc.currentBalance + "," +
                    acc.totalDeposit + "," +
                    acc.totalWithdraw);

    } catch (IOException e) {
        e.printStackTrace();
    }
}

private boolean accountExistsInCSV(String accNumber) {

    String filePath = "accounts.csv";

    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(filePath))) {
        String line;

        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");

            if (data.length > 0 && data[0].equals(accNumber)) {
                return true;  // ACCOUNT FOUND
            }
        }

    } catch (IOException e) {
        // File might not exist yet → no accounts saved
        return false;
    }

    return false;
}


    
    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed


    String accNumber = txtAccNo.getText();
    String name = txtName.getText();
    double amount = Double.parseDouble(txtInitialBalance.getText());

    // 1. CHECK in CSV file
    if (accountExistsInCSV(accNumber)) {
        JOptionPane.showMessageDialog(this,
                "This Account Number already exists in the system!",
                "Duplicate Account Number",
                JOptionPane.ERROR_MESSAGE);
        return;  // STOP
    }

    AccountInfo acc = new AccountInfo(accNumber, name, amount, amount, 0, 0);

    // 2. Save in HashMap (for current runtime)
    AccountInfo.accounts.put(accNumber, acc);

    // 3. Save to CSV
    saveAccountToCSV(acc);

    // 4. Refresh admin table
    adminPanel.refreshAdminTable();

    JOptionPane.showMessageDialog(this, "Account Created Successfully!");





    }//GEN-LAST:event_btnCreateAccActionPerformed

    
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
Dashboard dash = new Dashboard();
    dash.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtInitialBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInitialBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInitialBalanceActionPerformed

    private void txtInitialBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInitialBalanceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInitialBalanceKeyPressed

    private void txtInitialBalanceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtInitialBalanceInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInitialBalanceInputMethodTextChanged

    private void txtInitialBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInitialBalanceKeyTyped
            char c = evt.getKeyChar();
    String text = txtInitialBalance.getText();

    if (Character.isDigit(c)) return;          // allow numbers
    if (c == '.' && !text.contains(".")) return; // allow one decimal point

    evt.consume(); // block others
    }//GEN-LAST:event_txtInitialBalanceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtInitialBalance;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
